# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
name: library-app-compose
services:
  library-app:
    container_name: app
    image: library
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://library-postgresql:5432/library
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://library-postgresql:5432/library
      - JHIPSTER_SLEEP=15 # gives time for other services to boot before the application
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - library-postgresql

  library-postgresql:
    container_name: db
    image: postgres:14.5
    environment:
      - POSTGRES_USER=library
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: unless-stopped

  elasticsearch:
    container_name: elastic
    image: elasticsearch:7.17.10
    environment:
      - 'discovery.type=single-node'
    ports:
      - '9200:9200'

  kibana:
    container_name: kibana
    image: kibana:7.17.10
    ports:
      - '5601:5601'

  filebeat:
    container_name: filebeat
    image: elastic/filebeat:7.17.10
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro #config
      - /var/run/docker.sock:/var/run/docker.sock:delegated #enrich logs with extra info of the container
      - /var/lib/docker/containers:/var/lib/docker/containers:ro #logs folder
