# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
name: library-app-compose
services:
  library-app:
    container_name: app
    image: umigncarrillo/isa-library
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://library-postgresql:5432/library
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://library-postgresql:5432/library
      - JHIPSTER_SLEEP=5 # gives time for other services to boot before the application
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - library-postgresql

  library-postgresql:
    container_name: db
    image: postgres:14.5
    environment:
      - POSTGRES_USER=library
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: unless-stopped

  pwa:
    container_name: pwa
    build:
      context: /Users/nachoc-mini/Dev/isa/library-pwa
      dockerfile: Dockerfile
    ports:
      - 3000:3000
