version: '3.8'
name: jenkins
services:
  jenkins:
    container_name: jenkins
    #image: jenkins/jenkins / for mac m1 arm64 processor, build a custom image
    build:
      context: ./jenkins-arm64/
      dockerfile: Dockerfile
    ports:
      - 8090:8080
